### ISSUE TITLE
Code review from Team The Silicons

### ISSUE THREAD

**Issue by majovanilla** [sebastianlujan/ruby-enumerables#1]
Great job with your work so far!

We have a few suggestions:

- [x] Make sure you are using your own methods in the tests.
- [x] You can use the implicit return of Ruby.
- [x] Check for different types of inputs (blocks, arguments -numbers, ranges, arrays, etc)
- [x] In my inject, you will need to check for the parameters' type to make the method work

Keep it up!! You are almost done!

**Comment by sebastianlujan** [comment]
Thank you so much for your help!
I already implement all the changes and prepare for a PR
